package com.example.demo.config;

import com.example.demo.entity.User;
import com.example.demo.repository.UserRepository;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.context.annotation.Profile;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * Migrates seed users' password hash to one generated by the app's PasswordEncoder
 * so login with "password123" works (seed SQL hash may not match BCryptPasswordEncoder).
 */
@Component
@Profile("!test")
public class SeedPasswordMigrationRunner implements ApplicationRunner {

	private static final String SEED_PASSWORD_HASH = "$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy";
	private static final String SEED_PLAIN_PASSWORD = "password123";

	private final UserRepository userRepository;
	private final PasswordEncoder passwordEncoder;

	public SeedPasswordMigrationRunner(UserRepository userRepository, PasswordEncoder passwordEncoder) {
		this.userRepository = userRepository;
		this.passwordEncoder = passwordEncoder;
	}

	@Override
	@Transactional
	public void run(ApplicationArguments args) {
		List<User> usersWithSeedHash = userRepository.findByPasswordHash(SEED_PASSWORD_HASH);
		if (usersWithSeedHash.isEmpty()) {
			return;
		}
		String newHash = passwordEncoder.encode(SEED_PLAIN_PASSWORD);
		for (User user : usersWithSeedHash) {
			user.setPasswordHash(newHash);
		}
		userRepository.saveAll(usersWithSeedHash);
	}
}
